mode: wip
content:
  source:
    git:
      branch:
        fallback: master
        target: openshift-{MAJOR}.{MINOR}
      url: git@github.com:openshift/machine-config-operator.git
    specfile: machine-config-daemon.spec
name: machine-config-daemon
owners:
  - coreos-devel@redhat.com